////////////////////////////////////////////////////////////////
//                                                            //
//  DO NOT EDIT THIS FILE -- WRITE YOUR FUNCTIONS IN  tp3.c   //
//                                                            //
////////////////////////////////////////////////////////////////

// Reads the contents of "tp3.c", ignoring any main() function,
#define main no__main
#include "tp3.c"
#undef main

#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <errno.h>
#include <inttypes.h>

struct xx_ranctx { uint32_t a; uint32_t b; uint32_t c; uint32_t d; } xx_ranc;

uint32_t xx_ranval()
{
#define rot(x, k) (((x) << (k)) | ((x) >> (32 - (k))))
  uint32_t e = xx_ranc.a - rot(xx_ranc.b, 27);
  xx_ranc.a = xx_ranc.b ^ rot(xx_ranc.c, 17);
  xx_ranc.b = xx_ranc.c + xx_ranc.d;
  xx_ranc.c = xx_ranc.d + e;
  xx_ranc.d = e + xx_ranc.a;
  return xx_ranc.d;
}

void xx_raninit(uint32_t seed)
{
  xx_ranc.a = 0xf1ea5eed, xx_ranc.b = xx_ranc.c = xx_ranc.d = seed;
  for (uint32_t i = 0; i < 20; ++i)
    (void) xx_ranval();
}

FILE* xx_trace;
const char* xx_trace_name;

void xx_trace_init(const char* name)
{
  xx_trace_name = getenv("OUTPUT");
  if (!xx_trace_name)
    {
      static char tmp[30];
      strncpy(tmp, name, 30);
      strncat(tmp, ".trace", 30);
      xx_trace_name = tmp;
    }
  xx_trace = fopen(xx_trace_name, "w+");
  if (!xx_trace)
    {
      fprintf(stderr, "cannot open '%s' for writing: %s\n",
	      xx_trace_name, strerror(errno));
      exit(2);
    }

  time_t rawtime = time(NULL);
  struct tm *timeinfo = gmtime(&rawtime);
  char buffer[20];
  strftime(buffer, 80, "%F %T%n", timeinfo);

  int u = getuid();
  int r = rawtime & 0xffffff;
  fprintf(xx_trace, "%s\n%d\n%d\n", name, u, r);
  fputs(buffer, xx_trace);
  u ^= r;
  const char* s = getenv("SEED");
  if (s)
    u = atoi(s);
  xx_raninit(u);
}

void xx_trace_done()
{
  fclose(xx_trace);
  printf("please submit '%s'\n", xx_trace_name);
}

int xx_cmp(int a, int b)
{
  if (((a&1) == 0) && ((b&1) == 1))
    return -1;
  if (((a&1) == 1) && ((b&1) == 0))
    return 1;
  if (a < b)
    return -1;
  return a > b;
}

int main()
{
#if Q == 1
  xx_trace_init("tp3q1");
  const unsigned asize = 100;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = (int) xx_ranval();
  make_heap(a, asize);
  print_int_array(xx_trace, a, asize);
  make_heap(a, asize);
  print_int_array(xx_trace, a, asize);
  xx_trace_done();
#elif Q == 2
  xx_trace_init("tp3q2");
  const unsigned asize = 100;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = (int) xx_ranval();
  for (unsigned i = 0; i < 10; ++i)
    fprintf(xx_trace, "%d ", check_heap(a, i));
  fprintf(xx_trace, "%d ", check_heap(a, asize));
  make_heap(a, asize);
  fprintf(xx_trace, "%d\n", check_heap(a, asize));
  xx_trace_done();
#elif Q == 3
  xx_trace_init("tp3q3");
  const unsigned asize = 30;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = ((int) xx_ranval()) % 100;
  make_heap(a, asize);
  pretty_print_heap(xx_trace, a, asize);
  xx_trace_done();
#elif Q == 4
  xx_trace_init("tp3q4");
  unsigned asize = 30;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = ((int) xx_ranval()) % 100;
  make_heap(a, asize);
  do
    {
      if (asize % 3 == 0)
	pretty_print_heap(xx_trace, a, asize);
      fprintf(xx_trace, "pop_heap() == %d\n", pop_heap(a, &asize));
    }
  while (asize);
  xx_trace_done();
#elif Q == 5
  xx_trace_init("tp3q5");
  const unsigned asize = 100000;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = ((int) xx_ranval()) % (int) asize;
  heap_sort(a, asize);
  print_int_array(xx_trace, a, 100);
  print_int_array(xx_trace, a + asize - 100, 100);
  xx_trace_done();
#elif Q == 6
  xx_trace_init("tp3q6");
  const unsigned asize = 100000;
  int a[asize];
  for (unsigned i = 0; i < asize; ++i)
    a[i] = ((int) xx_ranval()) % (int) asize;
  heap_sort_cmp(a, asize, xx_cmp);
  print_int_array(xx_trace, a, 100);
  print_int_array(xx_trace, a + asize - 100, 100);
  xx_trace_done();
#else
  puts("Compile with -DQ=n, where n is the question number.");
#endif
  return 0;
}
